// Lists
export const CHANGE_LIST_TITLE = 'CHANGE_LIST_TITLE'
export const ADD_NEW_LIST = 'ADD_NEW_LIST'

// Cards
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const SWITCH_CARDS = 'SWITCH_CARDS'
export const CHENGE_STATUS = 'CHANGE_STATUS'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const ADD_DESC = 'ADD_DESC'
export const ADD_COVER_COLOR = 'ADD_COVER_COLOR'
export const CHANGE_TAG = 'CHANGE_TAG'

// checklist
export const ADD_CHECKLIST = 'ADD_CHECK_LIST'
export const CHANGE_TITLE_CHECKLIST = 'CHANGE_TITLE_CHECKLIST'
export const ADD_NEW_ITEM_CHECKLIST = 'ADD_NEW_ITEM_CHECKLIST'
export const CHEKED_ITEM_CHECKLIST = 'CHEKED_ITEM_CHECKLIST'
export const CHENGE_ITEM_TITLE_CHECKLIST = 'CHENGE_ITEM_TITLE_CHECKLIST'
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST'
export const DELETE_ITEM_CHECKLIST = 'DELETE_ITEM_CHECKLIST'

// Tags
export const CHANGE_TAG_TITLE = 'CHANGE_TAG_TITLE'
